name: API CI
on: [push]
# In case I had a mono-repo, I would have to use this configuration down
# on:
#  push:
#    -"./folder/***"
#    - ".github/workflows/api-ci.yml"

#defaults:
#  run:
#    working-directory: ./folder

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          # cache-dependency-path: ./package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test
